// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBYm9RtD9vVCa2acSv5knAmp3q6RG7bod0',
//     appId: '1:83681672893:web:5854e102fc4debc34781d4',
//     messagingSenderId: '83681672893',
//     projectId: 'ui-chatbot-24246',
//     authDomain: 'ui-chatbot-24246.firebaseapp.com',
//     databaseURL: 'https://ui-chatbot-24246-default-rtdb.firebaseio.com',
//     storageBucket: 'ui-chatbot-24246.appspot.com',
//     measurementId: 'G-1TNLPBC7LX',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCxYpBCtokHkXbfGUId4UMVcr6vDUg9uS4',
//     appId: '1:83681672893:android:06881f4d7f25e0b64781d4',
//     messagingSenderId: '83681672893',
//     projectId: 'ui-chatbot-24246',
//     databaseURL: 'https://ui-chatbot-24246-default-rtdb.firebaseio.com',
//     storageBucket: 'ui-chatbot-24246.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyApB6K0_3sURVK3JS7wRCfjRQ5cW0s_e_0',
//     appId: '1:83681672893:ios:cba944956bad82f24781d4',
//     messagingSenderId: '83681672893',
//     projectId: 'ui-chatbot-24246',
//     databaseURL: 'https://ui-chatbot-24246-default-rtdb.firebaseio.com',
//     storageBucket: 'ui-chatbot-24246.appspot.com',
//     iosBundleId: 'com.Oladisea.uiChatbot',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyApB6K0_3sURVK3JS7wRCfjRQ5cW0s_e_0',
//     appId: '1:83681672893:ios:0c2135758d9cabd94781d4',
//     messagingSenderId: '83681672893',
//     projectId: 'ui-chatbot-24246',
//     databaseURL: 'https://ui-chatbot-24246-default-rtdb.firebaseio.com',
//     storageBucket: 'ui-chatbot-24246.appspot.com',
//     iosBundleId: 'com.Oladisea.uiChatbot.RunnerTests',
//   );
// }
