import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_gemini/flutter_gemini.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import 'package:ui_chatbot/features/auth/presentation/data/repository/auth_repo.dart';
import 'core/service/consts.dart';
import 'features/auth/presentation/bloc/auth_bloc/auth_bloc.dart';
import 'features/chat/data/repository/chatbot_repository.dart';
import 'features/chat/presentation/bloc/chatbot_bloc.dart';
import 'features/history/chat_conversation.dart';
import 'features/splash_screen/splash_screen.dart';
import 'firebase_options.dart';


final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
//final GlobalKey<BottomNavBarScreenState> bottomNavKey = GlobalKey();
//const String apiKey = String.fromEnvironment('API_KEY');
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // await QueryHistoryDB.initialize();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  Gemini.init(apiKey: apiKey);

  final dir = await getApplicationDocumentsDirectory();
  final isar = await Isar.open(
    [ChatConversationSchema], // This schema is generated by build_runner
    directory: dir.path,
  );
  runApp(MultiBlocProvider(providers: [
    BlocProvider(create: (context)=> AuthBloc(authRepository: AuthRepository())),
    BlocProvider(create: (context)=> ChatbotBloc(repository: ChatbotRepository(), isar: isar))
    //BlocProvider(create: (context)=> QueryHistoryBloc(queryHistoryDB: QueryHistoryDB()))
  ],
  child: const MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(390, 844),
      minTextAdapt: true,
      builder: (context, child) {
        return const MaterialApp(
          debugShowCheckedModeBanner: false,
          home: SplashScreen(),
        );
      },
    );
  }
}
